-- brand.sql
INSERT INTO brand (name, popularity) VALUES
     ('celimax', 0),
     ('Torriden', 0),
     ('Anua', 0),
     ('COSRX', 0),
     ('VT', 0),
     ('INNISFREE', 0),
     ('ROUND LAB', 0),
     ('SKIN1004', 0),
     ('WAKEMAKE', 0),
     ('colorgram', 0),
     ('VDL', 0),
     ('TIRTIR', 0),
     ('A\'pieu', 0),
     ('3CE', 0),
     ('ETUDE', 0),
     ('Alternative stereo', 0),
     ('LANEIGE', 0),
     ('JUMISO', 0),
     ('Purito', 0),
     ('SUNGBOON EDITOR', 0),
     ('BANILA CO', 0),
     ('AHC', 0),
     ('AESTURA', 0),
     ('BEYOND', 0),
     ('hince', 0),
     ('SKINFOOD', 0),
     ('beplain', 0),
     ('Beauty of Joseon', 0),
     ('Foellie', 0),
     ('EDIT.B', 0),
     ('AIDA', 0),
     ('BRINGGREEN', 0),
     ('Lanbelle', 0),
     ('ma:nyo', 0),
     ('Arencia', 0),
     ('numbuzin', 0),
     ('goodal', 0),
     ('Dermatory', 0);